 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/routes", type: :request do
  
  # Route. As you add validations to Route, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Route.create! valid_attributes
      get routes_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      route = Route.create! valid_attributes
      get route_url(route)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_route_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      route = Route.create! valid_attributes
      get edit_route_url(route)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Route" do
        expect {
          post routes_url, params: { route: valid_attributes }
        }.to change(Route, :count).by(1)
      end

      it "redirects to the created route" do
        post routes_url, params: { route: valid_attributes }
        expect(response).to redirect_to(route_url(Route.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Route" do
        expect {
          post routes_url, params: { route: invalid_attributes }
        }.to change(Route, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post routes_url, params: { route: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested route" do
        route = Route.create! valid_attributes
        patch route_url(route), params: { route: new_attributes }
        route.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the route" do
        route = Route.create! valid_attributes
        patch route_url(route), params: { route: new_attributes }
        route.reload
        expect(response).to redirect_to(route_url(route))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        route = Route.create! valid_attributes
        patch route_url(route), params: { route: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested route" do
      route = Route.create! valid_attributes
      expect {
        delete route_url(route)
      }.to change(Route, :count).by(-1)
    end

    it "redirects to the routes list" do
      route = Route.create! valid_attributes
      delete route_url(route)
      expect(response).to redirect_to(routes_url)
    end
  end
end
